PACKAGE_NAME="tuxedo-drivers"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="clevo_acpi"
BUILT_MODULE_LOCATION[0]="src/"
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="tuxedo_keyboard"
BUILT_MODULE_LOCATION[1]="src/"
DEST_MODULE_LOCATION[1]="/updates"

BUILT_MODULE_NAME[2]="tuxedo_io"
BUILT_MODULE_LOCATION[2]="src/tuxedo_io/"
DEST_MODULE_LOCATION[2]="/updates"

MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"

AUTOINSTALL="yes"
